apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f kompose.yml convert --volumes hostPath
    kompose.service.type: loadBalancer
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: php
  name: php
spec:
  ports:
  - name: "8088"
    port: 8088
    targetPort: 8080
    protocol: TCP
  selector:
    io.kompose.service: php
  type: LoadBalancer
status:
  loadBalancer: {}
